export const SHOW_ALERT = 'SHOW ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
